### ISSUE TITLE
assh command is not working

### ISSUE THREAD

**Issue by natea** [ployground/ploy#10]
When I try to ssh into a newly created instance with the "assh" command, the following error occurs:

    $ ./bin/assh plone3-small-production
    /Users/nateaune/.buildout/eggs/pycrypto-2.0.1-py2.6-macosx-10.6-universal.egg/Crypto/Hash/SHA.py:6: DeprecationWarning: the sha module is deprecated; use the hashlib module instead
      import warnings
    /Users/nateaune/.buildout/eggs/pycrypto-2.0.1-py2.6-macosx-10.6-universal.egg/Crypto/Hash/MD5.py:6: DeprecationWarning: the md5 module is deprecated; use hashlib instead
      import warnings
    INFO: Instance 'plone3-small-production' available
    ERROR: Couldn't validate fingerprint for ssh connection.
    ERROR: Authentication failed.
    ERROR: Is the server finished starting up?

Do I need to specify a user or key somewhere in order for the ssh command to work?

Normally to ssh to the into the machine with this command, which works fine:

    ssh -i ~/id_rsa-gsg-keypair ubuntu@ec2-184-73-56-129.compute-1.amazonaws.com

**Comment by fschulze** [comment]
I **finally** documented the ``ssh-key-filename`` option on master now. With that you can point to the private key file you get when you create a keypair in the AWS console. Depending on the AMI image you use, you have to set the ``user`` option as well (``ubuntu`` for example).
