### ISSUE TITLE
Create an EBS volume from an EBS snapshot

### ISSUE THREAD

**Issue by natea** [ployground/ploy#4]
It would be really useful to be able to create new EBS volumes from an existing EBS snapshot.

The aws.conf file could have something like this:

    [instance:demo-server]
    keypair = default
    securitygroups = demo-server
    region = eu-west-1
    placement = eu-west-1a
    image = ami-a62a01d2
    snapshot = snap-2d8cd144 /dev/sdf
    startup_script = startup-demo-server
    fabfile = `fabfile.py`_

When you launch the instance demo-server, it would then create a new EBS volume from the snapshot "snap-2d8cd144" and attach it to the device /dev/sdf.

The info returned from the aws script would look something like this:
    INFO: Instance running.
    INFO: Instances DNS name ec2-184-73-240-104.compute-1.amazonaws.com
    INFO: Instances public DNS name ec2-184-73-240-104.compute-1.amazonaws.com
    INFO: Instances volume ID vol-58fc3031 created from snap-2d8cd144

**Comment by fschulze** [comment]
This was added a while ago (2010-12-09).
